// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Gmedianrowvec_rcpp
Rcpp::NumericVector Gmedianrowvec_rcpp(const arma::mat X, const double gamma, const double alpha, const int nstart, const double epsilon);
RcppExport SEXP _Gmedian_Gmedianrowvec_rcpp(SEXP XSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP nstartSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type nstart(nstartSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(Gmedianrowvec_rcpp(X, gamma, alpha, nstart, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// MedianCovMatRow_rcpp
Rcpp::NumericMatrix MedianCovMatRow_rcpp(const arma::mat X, const arma::rowvec Gmedian, const double gamma, const double alpha, const int nstart);
RcppExport SEXP _Gmedian_MedianCovMatRow_rcpp(SEXP XSEXP, SEXP GmedianSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP nstartSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Gmedian(GmedianSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type nstart(nstartSEXP);
    rcpp_result_gen = Rcpp::wrap(MedianCovMatRow_rcpp(X, Gmedian, gamma, alpha, nstart));
    return rcpp_result_gen;
END_RCPP
}
// MedianCovMatRowP_rcpp
Rcpp::NumericMatrix MedianCovMatRowP_rcpp(const arma::mat X, const arma::rowvec Gmedian, const double gamma, const double alpha, const int nstart);
RcppExport SEXP _Gmedian_MedianCovMatRowP_rcpp(SEXP XSEXP, SEXP GmedianSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP nstartSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Gmedian(GmedianSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type nstart(nstartSEXP);
    rcpp_result_gen = Rcpp::wrap(MedianCovMatRowP_rcpp(X, Gmedian, gamma, alpha, nstart));
    return rcpp_result_gen;
END_RCPP
}
// stoKmed_rcpp
Rcpp::List stoKmed_rcpp(const arma::mat X, const arma::mat Xtot, const arma::mat centers, const double gamma, const double alpha);
RcppExport SEXP _Gmedian_stoKmed_rcpp(SEXP XSEXP, SEXP XtotSEXP, SEXP centersSEXP, SEXP gammaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Xtot(XtotSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(stoKmed_rcpp(X, Xtot, centers, gamma, alpha));
    return rcpp_result_gen;
END_RCPP
}
// Weiszfeld_rcpp
Rcpp::List Weiszfeld_rcpp(const arma::mat X, const arma::rowvec weights, const double epsilon, int nitermax);
RcppExport SEXP _Gmedian_Weiszfeld_rcpp(SEXP XSEXP, SEXP weightsSEXP, SEXP epsilonSEXP, SEXP nitermaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type nitermax(nitermaxSEXP);
    rcpp_result_gen = Rcpp::wrap(Weiszfeld_rcpp(X, weights, epsilon, nitermax));
    return rcpp_result_gen;
END_RCPP
}
// MedianCovMatW_rcpp
Rcpp::List MedianCovMatW_rcpp(const arma::mat X, const arma::rowvec median_est, const arma::rowvec weights, const double epsilon, int nitermax);
RcppExport SEXP _Gmedian_MedianCovMatW_rcpp(SEXP XSEXP, SEXP median_estSEXP, SEXP weightsSEXP, SEXP epsilonSEXP, SEXP nitermaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type median_est(median_estSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type nitermax(nitermaxSEXP);
    rcpp_result_gen = Rcpp::wrap(MedianCovMatW_rcpp(X, median_est, weights, epsilon, nitermax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Gmedian_Gmedianrowvec_rcpp", (DL_FUNC) &_Gmedian_Gmedianrowvec_rcpp, 5},
    {"_Gmedian_MedianCovMatRow_rcpp", (DL_FUNC) &_Gmedian_MedianCovMatRow_rcpp, 5},
    {"_Gmedian_MedianCovMatRowP_rcpp", (DL_FUNC) &_Gmedian_MedianCovMatRowP_rcpp, 5},
    {"_Gmedian_stoKmed_rcpp", (DL_FUNC) &_Gmedian_stoKmed_rcpp, 5},
    {"_Gmedian_Weiszfeld_rcpp", (DL_FUNC) &_Gmedian_Weiszfeld_rcpp, 4},
    {"_Gmedian_MedianCovMatW_rcpp", (DL_FUNC) &_Gmedian_MedianCovMatW_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_Gmedian(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
