// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Gmedianrowvec_rcpp
Rcpp::NumericVector Gmedianrowvec_rcpp(const arma::mat X, const double gamma, const double alpha, const int nstart, const double epsilon);
RcppExport SEXP Gmedian_Gmedianrowvec_rcpp(SEXP XSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP nstartSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type nstart(nstartSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    __result = Rcpp::wrap(Gmedianrowvec_rcpp(X, gamma, alpha, nstart, epsilon));
    return __result;
END_RCPP
}
// MedianCovMatRow_rcpp
Rcpp::NumericMatrix MedianCovMatRow_rcpp(const arma::mat X, const arma::rowvec Gmedian, const double gamma, const double alpha, const int nstart);
RcppExport SEXP Gmedian_MedianCovMatRow_rcpp(SEXP XSEXP, SEXP GmedianSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP nstartSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Gmedian(GmedianSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type nstart(nstartSEXP);
    __result = Rcpp::wrap(MedianCovMatRow_rcpp(X, Gmedian, gamma, alpha, nstart));
    return __result;
END_RCPP
}
// MedianCovMatRowP_rcpp
Rcpp::NumericMatrix MedianCovMatRowP_rcpp(const arma::mat X, const arma::rowvec Gmedian, const double gamma, const double alpha, const int nstart);
RcppExport SEXP Gmedian_MedianCovMatRowP_rcpp(SEXP XSEXP, SEXP GmedianSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP nstartSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Gmedian(GmedianSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type nstart(nstartSEXP);
    __result = Rcpp::wrap(MedianCovMatRowP_rcpp(X, Gmedian, gamma, alpha, nstart));
    return __result;
END_RCPP
}
// stoKmed_rcpp
Rcpp::List stoKmed_rcpp(const arma::mat X, const arma::mat Xtot, const arma::mat centers, const double gamma, const double alpha);
RcppExport SEXP Gmedian_stoKmed_rcpp(SEXP XSEXP, SEXP XtotSEXP, SEXP centersSEXP, SEXP gammaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Xtot(XtotSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(stoKmed_rcpp(X, Xtot, centers, gamma, alpha));
    return __result;
END_RCPP
}
// Weiszfeld_rcpp
Rcpp::List Weiszfeld_rcpp(const arma::mat X, const arma::rowvec weights, const double epsilon, int nitermax);
RcppExport SEXP Gmedian_Weiszfeld_rcpp(SEXP XSEXP, SEXP weightsSEXP, SEXP epsilonSEXP, SEXP nitermaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type nitermax(nitermaxSEXP);
    __result = Rcpp::wrap(Weiszfeld_rcpp(X, weights, epsilon, nitermax));
    return __result;
END_RCPP
}
// MedianCovMatW_rcpp
Rcpp::List MedianCovMatW_rcpp(const arma::mat X, const arma::rowvec median_est, const arma::rowvec weights, const double epsilon, int nitermax);
RcppExport SEXP Gmedian_MedianCovMatW_rcpp(SEXP XSEXP, SEXP median_estSEXP, SEXP weightsSEXP, SEXP epsilonSEXP, SEXP nitermaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type median_est(median_estSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type nitermax(nitermaxSEXP);
    __result = Rcpp::wrap(MedianCovMatW_rcpp(X, median_est, weights, epsilon, nitermax));
    return __result;
END_RCPP
}
