# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gmedianrowvec_rcpp <- function(X, gamma = 2, alpha = 0.75, nstart = 1L, epsilon = 1e-8) {
    .Call('_Gmedian_Gmedianrowvec_rcpp', PACKAGE = 'Gmedian', X, gamma, alpha, nstart, epsilon)
}

MedianCovMatRow_rcpp <- function(X, Gmedian, gamma = 2, alpha = 0.75, nstart = 1L) {
    .Call('_Gmedian_MedianCovMatRow_rcpp', PACKAGE = 'Gmedian', X, Gmedian, gamma, alpha, nstart)
}

MedianCovMatRowP_rcpp <- function(X, Gmedian, gamma = 2, alpha = 0.75, nstart = 1L) {
    .Call('_Gmedian_MedianCovMatRowP_rcpp', PACKAGE = 'Gmedian', X, Gmedian, gamma, alpha, nstart)
}

stoKmed_rcpp <- function(X, Xtot, centers, gamma = 2, alpha = 0.75) {
    .Call('_Gmedian_stoKmed_rcpp', PACKAGE = 'Gmedian', X, Xtot, centers, gamma, alpha)
}

Weiszfeld_rcpp <- function(X, weights, epsilon = 1e-08, nitermax = 100L) {
    .Call('_Gmedian_Weiszfeld_rcpp', PACKAGE = 'Gmedian', X, weights, epsilon, nitermax)
}

MedianCovMatW_rcpp <- function(X, median_est, weights, epsilon = 1e-08, nitermax = 100L) {
    .Call('_Gmedian_MedianCovMatW_rcpp', PACKAGE = 'Gmedian', X, median_est, weights, epsilon, nitermax)
}

